"""add lacking_element to birth_profiles

Revision ID: c7fddaaf4915
Revises: ea0ef51324fa
Create Date: 2026-05-13 19:25:56.977593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7fddaaf4915'
down_revision: Union[str, Sequence[str], None] = 'ea0ef51324fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birth_profiles', sa.Column('lacking_element', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('birth_profiles', 'lacking_element')
    # ### end Alembic commands ###
